name: CI/CD for React Todo 

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: self-hosted
      # ...
      steps:
        # ...
        - name: Import Vault Secrets
          id: import-secrets
          uses: hashicorp/vault-action@v2
          with:
            url: http://18.233.166.63:8200
            token: ${{ secrets.VAULT_TOKEN }}
            secrets: |
                demoVault/data k1 ;
        # ...
